#!/usr/bin/env bash

REQS="apt-transport-https curl gnupg git wget build-essential xorg xinput x11-xserver-utils libxcursor-dev libxrandr-dev libxi-dev libimlib2-dev libxft-dev libfontconfig1 libx11-6 libxinerama-dev xserver-xorg-dev \
compton vim vim-gtk pcmanfm arandr lxappearance htop ranger tmux qt5ct feh pulseaudio pasystray pavucontrol pulsemixer pulseaudio-module-bluetooth network-manager dunst locate zathura sxiv scrot neofetch blueman arc-theme obsidian-icon-theme \
firmware-misc-nonfree firmware-netxen firmware-realtek" 
